name: Clymb Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium webdriver-manager
          pip install behave

      - name: Run Selenium tests
        env:
          BROWSER: ${{ matrix.browser }}
          TEST_URL: ${{ secrets.TEST_URL }} # Securely fetch the URL from GitHub Secrets
        run: |
          echo "Running tests on URL: $TEST_URL" # Debugging output to ensure the URL is fetched
          behave
