name: Clymb Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]  # Specify the browser

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium webdriver-manager behave

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libxss1 libx11-xcb1 libxcomposite1 libxcursor1 libxi6 libxtst6 \
            libpangocairo-1.0-0 libxrandr2 libatk-bridge2.0-0 libgbm1 libgtk-3-0 \
            libasound2 ttf-mscorefonts-installer

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y

      - name: Verify installation and environment
        run: |
          python --version
          pip list
          google-chrome --version

      - name: Run Selenium tests
        env:
          BROWSER: ${{ matrix.browser }}
          BASE_URL: ${{ secrets.BASE_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Running tests on URL: $BASE_URL with browser: $BROWSER"
          if [ "$BROWSER" == "chrome" ]; then
            export DISPLAY=:99.0
            google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 &
          fi
          behave --no-capture --no-capture-stderr --format=pretty
